//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imajes
    {
        public int CodeImaje { get; set; }
        public Nullable<int> CodeProduct { get; set; }
        public string PuthImaje1 { get; set; }
        public string PuthImaje2 { get; set; }
        public string PuthImaje3 { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
