//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComforTableEntities : DbContext
    {
        public ComforTableEntities()
            : base("name=ComforTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Imajes> Imajes { get; set; }
        public virtual DbSet<LikeProducts> LikeProducts { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<SearchOfUser> SearchOfUser { get; set; }
        public virtual DbSet<ShoppingCast> ShoppingCast { get; set; }
        public virtual DbSet<SubCategories> SubCategories { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
