//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchOfUser
    {
        public int CodeSearchOfUser { get; set; }
        public Nullable<int> CodeUser { get; set; }
        public string searchPath { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
